default_platform :ios

platform :ios do

    desc "Create signing certs and provisioning profiles if needed"
    lane :signing do
        cert(team_id: "79RY8264V4", development: true)
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", development: true)
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", development: true, platform: 'catalyst')

        cert(team_id: "79RY8264V4")
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", adhoc: true)
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", platform: 'catalyst')
    
        system "rm ../*.provisionprofile"
        system "rm ../*.mobileprovision"
        system "rm ../*.cer"
        system "rm ../*.p12"
        system "rm ../*.certSigningRequest"
    end

    def promptIncrementBuild
        if UI.confirm("Do you want to increase the build number before building the apps?")
            increment_build_number
        end
    end

    def copyFile(src, dest)
        File.write(dest, File.read(src))
    end

    desc "Submit a new Beta Build using FTP"
    desc "This will also make sure the profile is up to date"
    lane :ota do
        promptIncrementBuild
        gym(export_method: "ad-hoc")

        copyFile("../TorrentAdder/Info.plist", "../build/TorrentAdder.plist")

        ftp(host: "ftp.stanislaschevallier.fr",
            username: 'stanislaw',
            upload: {
                src: 'build/TorrentAdder.ipa',
                dest: '/www_ota/'
            }
        )
        ftp(host: "ftp.stanislaschevallier.fr",
            username: 'stanislaw',
            upload: {
                src: 'build/TorrentAdder.plist',
                dest: '/www_ota/'
            }
        )
  end
end
