default_platform :ios

platform :ios do

    desc "Create signing certs and provisioning profiles if needed"
    lane :signing do
        cert(team_id: "79RY8264V4", development: true)
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", development: true)
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", development: true, platform: 'catalyst')

        cert(team_id: "79RY8264V4")
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", adhoc: true)
        sigh(team_id: "79RY8264V4", app_identifier: "me.syan.TorrentAdder", platform: 'catalyst')
    
        system "rm ../*.provisionprofile"
        system "rm ../*.mobileprovision"
        system "rm ../*.cer"
        system "rm ../*.p12"
        system "rm ../*.certSigningRequest"
    end

    def promptIncrementBuild
        if UI.confirm("Do you want to increase the build number before building the apps?")
            increment_build_number
        end
    end

    desc "Submit a new build"
    lane :ota do
        promptIncrementBuild

        build_mac_app(
            export_method: "developer-id",
            export_options: {
                provisioningProfiles: {
                    "me.syan.TorrentAdder" => "me.syan.TorrentAdder DeveloperID"
                }
            }
        )

        Dir.chdir("..") do
            `unzip -p build/Magneto.ipa Payload/Magneto.app/Info.plist > build/Magneto.plist`
            `plutil -convert xml1 build/Magneto.plist`
            `deploy_ota build/Magneto.ipa build/Magneto.plist`
        end
    end
end
